### ISSUE TITLE
Transfer repository to organization

### ISSUE THREAD

**Issue by HaydenSD** [protonmail-desktop/application#105]
Hello,

I would like to start a discussion on whether or not we should move this project to it's own organization. It's grown pretty big, and I feel like everyone would benefit from an organization repository.

Tell me what you think below.

**Comment by kontrollanten** [comment]
Hi!

It may be a good idea. I haven't worked with Github organizations before, what kind of benefits will it add?

**Comment by BeatPlus** [comment]
The project was moved correctly to an organization, protonmail-desktop. From now on we will work this way.
