### ISSUE TITLE
Links not openable

### ISSUE THREAD

**Issue by Praethiax** [protonmail-desktop/application#108]
Hi.
Just got a mail with a confirmation link i had to open.
It didn't work. Was this feature removed to increase security or something like that?
Or is my version just broken.
I remeber old versions just opening the link in the default browser.

**Comment by kontrollanten** [comment]
Hi!

I assume this is happening in the enable-multiple-accounts branch? If yes, then it should be fixed by now :-) If no, please try it in the enable-multiple-accounts branch, if it still doesn't work just let me know which environment you're running. Thanks!

**Comment by Praethiax** [comment]
Just updated. It's working now. Thanks.
Case closed

**Comment by kontrollanten** [comment]
This is still an issue in Linux. I guess shell.openExternal instead of [open](https://npmjs.com/packages/open) will solve the problem.
