### ISSUE TITLE
Add landing screen

### ISSUE THREAD

**Issue by kontrollanten** [protonmail-desktop/application#115]
When starting the application for the first time it's just blank (except the sidebar). We should add some kind of simple landing screen that just welcomes the user.

**Comment by BeatPlus** [comment]
My initial thought was to ceate a settings page with different tabs. The first tab would be the _landing screen_ with some kind of introduction (e.g. info, changelog, proton blog updates for).

**Comment by kontrollanten** [comment]
I think the optimal solution would be to have something user friendly. Like "Hi and welcome to ProtonMail Desktop" and then a short intro and an arrow pointing to the "Add account" button. Just to make it crystal clear for the user how he should start using the application.

But it's a question of time. I think your approach works for now.

**Comment by BeatPlus** [comment]
Mmm, that is an interesting idea. What do you think about a simple page with the logo, the add account button, Intro | Settings | About links (small at the bottom). Plain background, minimalist style.

**Comment by kontrollanten** [comment]
I think it would be enough with the logo and add account button. Regarding the links you proposed I don't think Intro is necessary, and the other two can the user reach via the application menus. What do you think about that?

I'm not a designer but I can see if I can find someone at Fiverr to create a good looking (and minimalistic) landing page.

**Comment by BeatPlus** [comment]
The simplest design as you suggest is the way to go.

I am not a designer either but I have some basic knowledge and I will be able to do it without problems.

**Comment by BeatPlus** [comment]
#132 implemented this feature.
