### ISSUE TITLE
Is it possible to let app start with minimized window?

### ISSUE THREAD

**Issue by sudoyang** [protonmail-desktop/application#120]
I am running the app on a ubuntu 16.04 machine. 

Thanks!

**Comment by kontrollanten** [comment]
I assume that would be possible if we read a parameter which you can pass if you run the app via terminal. What is the purpose of starting it minimized?

**Comment by sudoyang** [comment]
I think that maybe it is a good idea if the app can store username/password and start with system, with the window minimized. It is just like a service and whenever you need it, you can bring it in front of you.

**Comment by BeatPlus** [comment]
The desktop will never store user's password for security issues. I don't see how this could improve user experience

**Comment by sudoyang** [comment]
got it. I thought in a different way.
