### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by AlaricReinhard** [protonmail-desktop/application#125]
Im a noob, cant figure out how to run on MacOS.

**Comment by kontrollanten** [comment]
We will soon release built packages ready to install. But if you don't want to wait, you can do the following.

Be sure to have NodeJS (I recommend version 8) installed.
```
$ npm install yarn -g
$ yarn install
$ yarn run start
```

**Comment by kontrollanten** [comment]
@AlaricReinhard You can now download the latest release for MacOS at https://github.com/protonmail-desktop/application/releases Let me know if you have any more troubles.

**Comment by AlaricReinhard** [comment]
Amazing build. Needed this badly thank you!
