### ISSUE TITLE
Window always open in minified mode when opening from the dock icon

### ISSUE THREAD

**Issue by roipoussiere** [protonmail-desktop/application#126]
On Ubuntu 16.04

When I re-open ProtonMail from the dock icon, the window starts in minified mode in the task bar:

![](https://i.imgur.com/STXwcBl.png)

I need click again on the tab to open actually the window.

**Comment by roipoussiere** [comment]
Update: the window actually opens in maximized mode, but it's always in the background, behind all other windows. So we can't see it if an other application is already running.

**Comment by kontrollanten** [comment]
@roipoussiere Are you still experiencing this? We released a new version today with a lot of improvements. If the problem still occurs, please let me know which window manager you're running.

**Comment by roipoussiere** [comment]
Seems fixed, thank you!
And the new release looks awesome ;)
