### ISSUE TITLE
Cannot find module 'gulp-sass'

### ISSUE THREAD

**Issue by nobicycle** [protonmail-desktop/application#128]
Thanks for protonmail-desktop. I've been using it for several months but I recently did a "git pull origin". There was a small update, but now "npm start" produces 
$ npm start

> > protonmail-desktop@0.5.1 start /home/archives/Office/Email/ProtonMail/Protonmail-git
> > gulp start --env=development
> 
> module.js:529
>     throw err;
>     ^
> 
> Error: Cannot find module 'gulp-sass'
>     at Function.Module._resolveFilename (module.js:527:15)
>     at Function.Module._load (module.js:476:23)
>     at Module.require (module.js:568:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/archives/Office/Email/ProtonMail/Protonmail-git/tasks/build_app.js:2:14)
>     at Module._compile (module.js:624:30)
>     at Object.Module._extensions..js (module.js:635:10)
>     at Module.load (module.js:545:32)
>     at tryModuleLoad (module.js:508:12)
>     at Function.Module._load (module.js:500:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! protonmail-desktop@0.5.1 start: `gulp start --env=development`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the protonmail-desktop@0.5.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 

_**Git info:**_

> git show
> commit fc2fcb5575f91294738bb2799da3a3f71f378e9f (HEAD -> master, origin/master, origin/HEAD)
> Merge: 4082d3f 674efbc
> Author: Matthew <imatcore@gmail.com>
> Date:   Fri Sep 8 22:30:02 2017 +0200
> 
>     Merge pull request #122 from protonmail-desktop/appveyor-integration
>     
>     Appveyor integration
> 
> [adrian@tower Protonmail-git]$ git list
> git: 'list' is not a git command. See 'git --help'.
> 
> The most similar commands are
> 	bisect
> 	rev-list
> [adrian@tower Protonmail-git]$ git branch
> * master
> [adrian@tower Protonmail-git]$ git tag
> 0.3.0
> v0.1.1
> [adrian@tower Protonmail-git]$ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> 
> nothing to commit, working tree clean

**Comment by kontrollanten** [comment]
Did you run `npm install` before `npm start`?

**Comment by nobicycle** [comment]
Actually no. Sorry about that. But now I have and the log is here

https://paste.pound-python.org/show/LLrtRuBzS3qvZ7SFKj3y/

Starting still fails as below:
(Note I do have a package 'electron' 1.6.11 installed under Arch Linux but is was never a problem in the past with protonmail-desktop)

> $ npm start
> 
> > protonmail-desktop@0.5.1 start /home/archives/Office/Email/ProtonMail/Protonmail-git
> > gulp start --env=development
> 
> [22:57:36] Using gulpfile /home/archives/Office/Email/ProtonMail/Protonmail-git/gulpfile.js
> [22:57:36] Starting 'bundle'...
> [22:57:36] Starting 'sass'...
> [22:57:36] Starting 'watch'...
> [22:57:36] Finished 'watch' after 5.98 ms
> 'BrowserWindow' is imported from external module 'electron' but never used
> 'shell' is imported from external module 'electron' but never used
> [22:57:36] Finished 'bundle' after 133 ms
> [22:57:36] Finished 'sass' after 148 ms
> [22:57:36] Starting 'build'...
> [22:57:36] Finished 'build' after 16 μs
> [22:57:36] Starting 'start'...
> [22:57:36] Finished 'start' after 3.76 ms
> Electron could not be found. No hard resets for you!
>

**Comment by BeatPlus** [comment]
Could you try a clean install? It might be a problem with dependencies installation

**Comment by kontrollanten** [comment]
Feel free to re-open this issue if you still experiencing problems. If you just want to use the application, we're now releasing binaries when new updates are available.
