### ISSUE TITLE
JS error upon second app start

### ISSUE THREAD

**Issue by WatchGintama** [protonmail-desktop/application#146]
![protonmail desktop_2017-10-20_13-26-20](https://user-images.githubusercontent.com/13687535/31845274-b8c02d98-b59a-11e7-926f-3cf02260439b.png)

Javascript error when I close the window and open it again through start menu.

**Comment by kontrollanten** [comment]
Thanks for your report. Is this version 0.5.1 installed from a binary?

**Comment by WatchGintama** [comment]
https://github.com/protonmail-desktop/application/releases/download/v0.5.1/protonmail-desktop-setup-0.5.1.exe

Yes, this one.

**Comment by BeatPlus** [comment]
It also occurs on my W10. I will work on this
