### ISSUE TITLE
Add option to toggle left sidebar

### ISSUE THREAD

**Issue by simoniz0r** [protonmail-desktop/application#148]
It would be nice if there were an option to hide the left sidebar; I use one account with Protonmail, so having the sidebar open at all times is kind of just a waste of space for me.

Thanks!

**Comment by BeatPlus** [comment]
Great idea, I will implement this through a shortcut in the short-term and later in the settings panel

**Comment by HaydenSD** [comment]
Like this!

**Comment by kontrollanten** [comment]
Thanks @BeatPlus for implementing this #153. It's now possible to toggle the sidebar with Ctrl + Shift + H.
