### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by shumashv1** [protonmail-desktop/application#160]
On Windows 10, version 1709, the following error occurs if you attempt to reopen the app from a shortcut while its running in the background (note that you can't tell that it's running in the background if in tablet mode):

![javascript error](https://user-images.githubusercontent.com/1964800/34884051-c72445e8-f778-11e7-8b5c-7941cef799e3.JPG)

**Comment by kontrollanten** [comment]
Thanks for reporting! This should be fixed in the latest code. Are we ready to deploy that, @BeatPlus ?

**Comment by BeatPlus** [comment]
Yes, latest version is ready

**Comment by shumashv1** [comment]
Thx.  I'll try it out right away.

**Comment by shumashv1** [comment]
BTW, where's the download available?

From: shumash geely
Sent: Sunday, January 14, 2018 7:14 AM
To: protonmail-desktop/application
Subject: RE: [protonmail-desktop/application] JavaScript Error (#160)

Thx.  I'll try it out right away.

**Comment by kontrollanten** [comment]
@shumashv1 it's on it's way. The build failed earlier, but soon it should be reachable at https://github.com/protonmail-desktop/application/releases

**Comment by shumashv1** [comment]
Thx. I'll keep a lookout for it.

Larry Schuster

**Comment by kontrollanten** [comment]
https://github.com/protonmail-desktop/application/releases/tag/v0.5.4

**Comment by shumashv1** [comment]
Perfect. Thx
