### ISSUE TITLE
Relocate star/unstar toggle

### ISSUE THREAD

**Issue by shumashv1** [protonmail-desktop/application#161]
The star/unstar toggle is located right where a right-handed person touches to open an email. How about relocating it under the date?

**Comment by shumashv1** [comment]
The star/unstar toggle is located right where a right-handed person touches to open an email.  How about relocating it under the date?

**Comment by kontrollanten** [comment]
Thanks for your feedback! ProtonMail Desktop is just a wrapper for the web client though, so please fill an issue at https://github.com/protonmail/webclient
