### ISSUE TITLE
support for appimaged

### ISSUE THREAD

**Issue by Lvaskz** [protonmail-desktop/application#162]
hi, i am using linuxmint 18.03, 64 bits, cinnamon. Actually i installed the appimage daemon called appimaged.
This is appimaged "appimaged is an optional daemon that watches locations like ~/bin and ~/Downloads for AppImages and if it detects some, registers them with the system, so that they show up in the menu, have their icons show up, MIME types associated, etc. It also unregisters AppImages again from the system if they are deleted. If firejail is installed, it runs the AppImages with it."https://github.com/AppImage/AppImageKit
Many appimages, using this can register the icon in the system menu without installing, only putting the appimages on the bin folder or download folder, etc but many icons appimages are not recognized by appimaged, like rambox, vlc, nextcloud, protonmail etc.
By that reason i request if this is posible, protonmail can be supported by appimaged

**Comment by kontrollanten** [comment]
Hi!

As I've understood the concept of appimaged, it's just an daemon that searches your disk for appimage files. We already releases appimage files, so this should work right now. Have you tried download it from https://github.com/protonmail-desktop/application/releases ?

**Comment by Lvaskz** [comment]
yes, i did, but the problem is that the icon is missing from application menu. Appimaged recognized protonmail but not the icon, thats why I request this.

**Comment by kontrollanten** [comment]
It seems that the ProtonMail Desktop application needs to add icons in the system since appimaged doesn't do this. I've done a bit of research but couldn't find any easy way to do this with electron-builder. @probonopd do you know how this can be solved?

**Comment by probonopd** [comment]
The optional `appimaged` daemon extracts the icons found inside the AppImage in the `usr/share/icons/...` hierarchy, and puts them into `$HOME/.local/share` hierarchy. It also removes them again when the AppImage is removed.

Actually, the icon gets extracted correctly to 

```
$HOME/.local/share/icons/default/512x512/apps/appimagekit_003d3e803b7e43a5f4ee559be432eb4c_protonmail-desktop.png
``` 

on my system, and the desktop file generated by `appimaged` reads

```
me@host:~$ cat .local/share/applications/appimagekit_003d3e803b7e43a5f4ee559be432eb4c-protonmail-desktop.desktop 

[Desktop Entry]
(...)
Icon=appimagekit_003d3e803b7e43a5f4ee559be432eb4c_protonmail-desktop

```

So everything looks correct. Please log out of your desktop session and log in again, and see whether this solves it.

**Comment by probonopd** [comment]
Further analysis shows:

```
me@host:~$ file /tmp/.mount_OqtGsV/usr/share/icons/default/512x512/apps/protonmail-desktop.png 
/tmp/.mount_OqtGsV/usr/share/icons/default/512x512/apps/protonmail-desktop.png: PNG image data, 1024 x 1024, 8-bit/color RGBA, non-interlaced
```

This is not correct. A 512x512 pixel png is expected in `usr/share/icons/default/512x512`, as the name implies.

**Comment by probonopd** [comment]
Furthermore, for whatever reason, the icon does not get extracted correctly by `appimaged`, resulting in a 0 KB file:

```
# The original inside the AppImage
me@host:~$ ls -lh /tmp/.mount_OqtGsV/usr/share/icons/default/512x512/apps/protonmail-desktop.png 
-rw-rw-r-- 1 root 2000 433K Jan 14 22:11 /tmp/.mount_OqtGsV/usr/share/icons/default/512x512/apps/protonmail-desktop.png

# The one extracted by appimaged
me@host:~$ ls -lh .local/share/icons/default/512x512/apps/appimagekit_003d3e803b7e43a5f4ee559be432eb4c_protonmail-desktop.png 
-rw-r--r-- 1 me me 0 Jan 20 11:04 .local/share/icons/default/512x512/apps/appimagekit_003d3e803b7e43a5f4ee559be432eb4c_protonmail-desktop.png
```

This is most likely an `appimaged` bug.

Is there a reason why this is still a type-1 AppImage? The type-2 format is what the most recent versions of electron-builder are putting out, and it is much better supported by `appimaged`.

**Comment by kontrollanten** [comment]
Thank's for your help, @probonopd. I guess it's electron-builder who decides whether it'll be a type-1 or type-2 format? 

I've updated electron-builder and will remove the 512x512.png so electron-builder will use the MacOS X icon instead. Hopefully this will solve the problem.

**Comment by kontrollanten** [comment]
@Lvaskz can you try do download the latest pre-release from https://github.com/protonmail-desktop/application/releases/tag/v0.5.5 and see if it works? For me the icon is displayed correctly after I've first opened the AppImage.

**Comment by Lvaskz** [comment]
well, the icon appears but is some different, see it, it looks like other aplication
![proton](https://user-images.githubusercontent.com/29207169/35195352-debe7956-fe87-11e7-9e8b-769b98bdd9d5.png)

**Comment by Lvaskz** [comment]
There are a mix of icon. See the task bar

**Comment by probonopd** [comment]
> I guess it's electron-builder who decides whether it'll be a type-1 or type-2 format?

The latest version should produce type-2.

**Comment by kontrollanten** [comment]
@Lvaskz Well that's Electrons default icon. Strange. I have to look deeper into this.

**Comment by Lvaskz** [comment]
Have you been able to find out something about the correct icon?

**Comment by kontrollanten** [comment]
No, I'm not able to reproduce this. Are you sure you don't have to two different versions installed of the client?

**Comment by Lvaskz** [comment]
No, I haven't.  What desktop are you using?

**Comment by kontrollanten** [comment]
Cinnamon, the latest I guess. I can't see the version right now. And you?

**Comment by Lvaskz** [comment]
It suppost 3.6 version, but I must to check it. I suspect that this issue must to be in the desktop version, if kde and gnome not reproduce this issue then I think it could be cinnamon desktop. I must to proof my theory and use kde or gnome desktop.

**Comment by Lvaskz** [comment]
Greetings, I've been testing this in ubuntu gnome 18 04 and 16.04 and the problem remains and the mate also. The icon that appears is of electrons. So I do not think it's the desktop version. My suspicions vanished, apparently does not have to do with the version of the desktop.

**Comment by bnscv** [comment]
Just to confirm that the icon problem also happens on KDE, using Kubuntu 18.04.

**Comment by kontrollanten** [comment]
No, not really. We're working on a complete new version of the application in a separate branch. But I haven't got much time to work on that lately since I've been busy with work and private life. I hope we can do a pre release of version 1 soon, then I'll write here to let you try if the new version solves the problem.

**Comment by kontrollanten** [comment]
@Lvaskz Sorry for the delay, we've now published a pre release. If you want to, you can download it and see if works better.

**Comment by Lvaskz** [comment]
hi, same issue with beta release

**Comment by kontrollanten** [comment]
Okay, thanks

**Comment by kontrollanten** [comment]
I found

```
  • default Electron icon is used reason=application icon is not set
  • no native production dependencies
``` 

In the build log https://circleci.com/gh/protonmail-desktop/application/66 I guess it can be related :thinking: I think I have a fix for it, but I need to try it in a clean environment first.

**Comment by kontrollanten** [comment]
A new release https://github.com/protonmail-desktop/application/releases/tag/v1.0.0-beta.5 where the icon should be fixed for AppImaged 🙏

**Comment by Lvaskz** [comment]
Hi, yes,  now is working well with appimagelauncher
 Thanks for your efforts, very appreciated
