### ISSUE TITLE
No focus when switching windows

### ISSUE THREAD

**Issue by mighty-pirate** [protonmail-desktop/application#168]
When switching away from the application, then back; the browser doesn't seem to have focus and needs to be clicked with the mouse or tab pressed 3 times so hotkeys can be used or the command palette activated. I think this is because the accounts sidebar is getting the focus on window activation.

**Comment by kontrollanten** [comment]
Thanks for your input!

There's a PR for this here https://github.com/protonmail-desktop/application/pull/169

Hopefully we can merge it this week.

**Comment by BeatPlus** [comment]
I will review this and merge if possible by Saturday

**Comment by mighty-pirate** [comment]
Ok, great. Thanks a lot.

**Comment by mighty-pirate** [comment]
I've tried the new version and the browser is keeping focus. Thanks so much 👍
