### ISSUE TITLE
macOS Sierra 10.12.6 - 4k monitor icon broken

### ISSUE THREAD

**Issue by dtolb** [protonmail-desktop/application#175]
Loving the app so far! 

I'm running macOS Sierra 10.12.6 with a 4k monitor (no scaling).  The app icon is broken at this resolution and shows the default icon for macOS.

![screen shot on 2018-04-09 at 09_59_30](https://user-images.githubusercontent.com/6805534/38502181-c306c122-3bdc-11e8-89e8-2f73f1ab2b69.png)

I was able to fix it locally by [converting the .png to an icon](https://iconverticons.com/online/) and following the instructions to [change the icon](http://www.idownloadblog.com/2014/07/16/how-to-change-app-icon-mac/).

**Comment by kontrollanten** [comment]
Thanks for reporting! We'll try to fix this soon

**Comment by kontrollanten** [comment]
Sorry for late response. Can you try the latest beta to see if it works?

**Comment by dtolb** [comment]
no issue recently!
