### ISSUE TITLE
Only first tab is functional after app restart

### ISSUE THREAD

**Issue by ThisIsMissEm** [protonmail-desktop/application#176]
Hi!

I've noticed that if I quick the application, then reopen it, then only the first tab is functional, the others just render as:
![screen shot 2018-04-18 at 2 03 30 pm](https://user-images.githubusercontent.com/30827/38930770-4ba5a288-4311-11e8-914b-3fb697b89a09.png)

I've tried debugging it, but can't get anything to work. Any ideas?

**Comment by BeatPlus** [comment]
Hi, are you using the binary or source?

**Comment by ThisIsMissEm** [comment]
Binary.

**Comment by kontrollanten** [comment]
This is a bug and should be solved by our [React version](https://github.com/protonmail-desktop/application/projects/1)

**Comment by kontrollanten** [comment]
@ThisIsMissEm We've pre-released our React version now, you can download it at https://github.com/protonmail-desktop/application/releases/tag/v1.0.0-beta.1
