### ISSUE TITLE
False Positive (Virus Total/Hybrid Analysis)

### ISSUE THREAD

**Issue by antuketot76** [protonmail-desktop/application#177]
Find out the file downloaded detected as below.

![image](https://user-images.githubusercontent.com/33280865/39414600-76f459f4-4c74-11e8-942a-f7317b5be6d6.png)

SHA-256 - 9619df23415da415550e20e3e442f998e85496be817062d946bc0af00ea89950
File Name - protonmail-desktop-setup-0.5.8.exe
File Size - 78.28 MB
Date Scanned : 2018-04-30 03:22:08 UTC

GitHub File : [HERE](https://github.com/protonmail-desktop/application/releases/download/v0.5.8/protonmail-desktop-setup-0.5.8.exe)

Virus Total Result : [HERE](https://www.virustotal.com/#/file/9619df23415da415550e20e3e442f998e85496be817062d946bc0af00ea89950/detection)

**Comment by kontrollanten** [comment]
Thanks! What does "HW32.Packed.3BAF" mean? I couldn't find any information about it

**Comment by antuketot76** [comment]
Hey, below are result by Hybrid Analysis.
Hope that this will help you to analyze this "HW32.Packed.3BAF"
Hybrid Analysis Result : [HERE](https://www.hybrid-analysis.com/sample/9619df23415da415550e20e3e442f998e85496be817062d946bc0af00ea89950/5ae79d5b7ca3e15c0b392163)
![image](https://user-images.githubusercontent.com/33280865/39454852-901c3a06-4d18-11e8-943f-c3037d742c6b.png)
![image](https://user-images.githubusercontent.com/33280865/39454878-ad820bb6-4d18-11e8-866c-6dca3643a561.png)

**Comment by kontrollanten** [comment]
1/64 anti virus services says it's malicious. I don't why it's triggered as malicious and therefore it's hard to find any fix for this. Any help would be appreciated.

**Comment by kontrollanten** [comment]
This is now solved. I'll see if we can build a CI job that scans the files every week to detect this early, but I'm closing this issue since it's resolved.
