### ISSUE TITLE
Desktop client not working 

### ISSUE THREAD

**Issue by Ghost-Recon131** [protonmail-desktop/application#179]
I'm not sure why but an hour ago the Protonmail desktop client just decided to stop working and stay on the default screen without showing the login screen. I've tried to uninstall the app which didn't work then I used RevoUninstaller Pro to clean all traces of the program and it still didn't work. Any ideas how to solve this? I'm using the windows version and I'm running the latest version of Windows 10 Pro
<img width="971" alt="capture" src="https://user-images.githubusercontent.com/40227626/41956510-342f578c-7a27-11e8-9fa6-f368ffa04ea3.PNG">

**Comment by Ghost-Recon131** [comment]
opps sorry accidentally closed it

**Comment by kontrollanten** [comment]
Strange. This can happen when there's no internet connection (or if https://mail.protonmail.com/login is unreachable), but I guess you can reach https://mail.protonmail.com/login in your browser?

Can you open the application from the command line and see if there's any errors logged in the CLI?

**Comment by Ghost-Recon131** [comment]
Yeah I can, I've also made sure I've haven't got VPNs running

**Comment by Ghost-Recon131** [comment]
I've done a few more uninstall and restarts and the app is working again. Perhaps there was a small glitch on the Protonmail server. Thanks for your help!

**Comment by kontrollanten** [comment]
Okay. We're working on a new client which will handle those cases better. Let me know if you're facing this issue again!

**Comment by nick-lehmann** [comment]
The issue might not have been caused by the client but rather by the server. I received an email from Protonmail that their servers were under heavy DDoS attacks the last days but the issue is now fixed.
