### ISSUE TITLE
Allow to use https://beta.protonmail.com/inbox

### ISSUE THREAD

**Issue by LM1LC3N7** [protonmail-desktop/application#180]
Can you allow this new URL ?

https://beta.protonmail.com/inbox

**Comment by kontrollanten** [comment]
Sorry for late answer. I've filled up with porting the client to React. That will make the client more configurable. I'm adding this as a feature in the React client and hopefully I can deploy a beta soon. I'll let you know :)

**Comment by LM1LC3N7** [comment]
Ok thanks for the news!

**Comment by kontrollanten** [comment]
@LM1LC3N7 We've released our own beta where it's possible to opt in for beta.protonmail.com https://github.com/protonmail-desktop/application/releases/tag/v1.0.0-beta.1

![image](https://user-images.githubusercontent.com/6680299/49092899-506ffa00-f263-11e8-9866-f096c8caadc8.png)
