### ISSUE TITLE
Copying of hyperlinks

### ISSUE THREAD

**Issue by beanaroo** [protonmail-desktop/application#183]
At the moment, right-clicking on hyperlinks in emails does nothing.

It would be great if a context menu was provided to copy a link. (like in Slack and Hiri)

*Workaround*: Dragging and dropping the link works for now.

**Comment by kontrollanten** [comment]
Thanks for reporting! We'll put that on the list!

**Comment by kontrollanten** [comment]
@beanaroo Which OS are you using? For me it works in MacOS 10.14.

**Comment by BeatPlus** [comment]
Right click is not working for me in react beta release, a similar fix to [this one](https://github.com/sindresorhus/electron-context-menu/issues/37) should work. I'll work on it

**Comment by vladimiry** [comment]
[Here](https://github.com/vladimiry/email-securely-app/blob/6d99e927100aa4574902c3f49bf53feeba7d2e8b/src/electron-main/web-content-context-menu.ts) is the relatively simple solution that works for BrowserWindow + webviews with Electron v3. Keep in mind that `initWebContentContextMenu` function needs to be called before BrowserWindow creating. This solution also copes well with [this](https://github.com/electron/electron/issues/15219) Electron v3 bug.

**Comment by kontrollanten** [comment]
v1.0.0-beta.4 is released where this should be fixed. I've no Windows computer, but I could reproduce it and verify the fix in VirtualBox. Please reopen if the problem still occurs.
