### ISSUE TITLE
[Bug] Window stuck alwaysOnTop

### ISSUE THREAD

**Issue by UnreaI** [protonmail-desktop/application#192]
The app is always on top of other windows, have to click minimize every time. >:

**Comment by kontrollanten** [comment]
Thanks for your report! Which OS version and which version of ProtonMail Desktop are you using?

**Comment by UnreaI** [comment]
@kontrollanten Windows 10 version 1803, 1.0.0-beta.3

**Comment by kontrollanten** [comment]
@UnreaI If you to the menu and choose Help > Always on top, will that fix it? Ctrl+Shift+T should also work

**Comment by UnreaI** [comment]
Yes, Ctrl+Shift+T works! Thank you :)
