### ISSUE TITLE
Can't resume writing draft messages

### ISSUE THREAD

**Issue by notramo** [protonmail-desktop/application#198]
It is not possible to edit or view a draft message. It says "Script execution is forbidden" in the same style as it says when "Message sent", "Servers are unreachable", etc.

**Comment by BeatPlus** [comment]
This sounds to me like a ProtonMail bug, otherwise the window you mention would be different to "message sent". 

Have you tried reproducing it again?

**Comment by notramo** [comment]
I tried it from a WebKitGTK and a Gecko browser, and it works perfectly in both.

**Comment by kontrollanten** [comment]
But it's still not working in ProtonMail Desktop? If not, which version are you using?

**Comment by notramo** [comment]
Oops. I was using 0.5.8 (the Arch Linux package is outdated, and I didn't checked it). It still exists in 0.5.9, but it works in 1.0.0-beta.3.
I'm sorry for wasting your time!
