### ISSUE TITLE
Add autologin (or even better; sign in at startup)

### ISSUE THREAD

**Issue by lukapercic** [protonmail-desktop/application#200]
![image](https://user-images.githubusercontent.com/4706356/50560447-25187900-0d01-11e9-84dd-786a8b94da71.png)
I downloaded this promising utility because i hoped i wouldn't need to sign up everytime (like i do on the web). Thats not the case, and its in fact even harder to to sign up everytime (no password save)

**Comment by kontrollanten** [comment]
It's by design that we don't store the password. There's already an issue where we've discussed this #149 

You can try https://github.com/vladimiry/email-securely-app Which I think has support for ProtonMail and single sign in.

**Comment by danger89** [comment]
OK< too bad bye bye. I switch to his app. I'm using Protonmail desktop on my OWN desktop, no risk that people access my desktop.
