### ISSUE TITLE
When I try to install 0.5.9, I get this error

### ISSUE THREAD

**Issue by starndust31** [protonmail-desktop/application#201]
![new bitmap image](https://user-images.githubusercontent.com/25423730/50566148-2f2f7d00-0ceb-11e9-9d3a-8e4e2a4d0cb1.jpg)

**Comment by kontrollanten** [comment]
Which OS and version are you using? Can you try to install the latest pre release 1.0.0-beta.3?

**Comment by starndust31** [comment]
I am using windows 10 64-bit Version 1803 (OS Build 17134.472). The pre release 1.0.0-beta.3 does install correctly, but notifications didn't work. I was hoping that if I installed the latest release which is 0.5.9 then it would be stabler and perhaps notifications would work there. However, I instead get this error when trying to install 0.5.9

**Comment by starndust31** [comment]
Ok, I tried again and it works now. Just thought I'd say that.
