### ISSUE TITLE
Can't 'snap resize' window on ubuntu 18.04

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [protonmail-desktop/application#203]
Hi,
I just switched from 16.04 to 18.04 and installed your app. I was previously on unity but now on gnome-shell 3.28.3
I noticed I can snap resize the app to fullscreen (super + uparrow) but I can't seem to snap it on the sides (make it take only half the screen) using super+horizontalarrows

Any idea how I could fix this ?

**Comment by kontrollanten** [comment]
Hi! I'm sorry but I don't know how that can be fixed or where the issue is. It sounds like it's a feature that shouldn't depend on the application. I guess you haven't got it working yet?

**Comment by thiswillbeyourgithub** [comment]
Nope, and I am not a dev so I have no idea how to help :/

**Comment by kontrollanten** [comment]
It sounds like you've got a good reason to start ;-) I'll keep this open and hope for help from the community.
