### ISSUE TITLE
Dark theme setting has no effect

### ISSUE THREAD

**Issue by didrip** [protonmail-desktop/application#204]
When checking the options "dark theme" in settings (bottom left), the appearance is not changed.

ProtonMail Desktop v1.0.0-beta3
Ubuntu 18.10 + GNOME

**Comment by kontrollanten** [comment]
It seems to be a bit broken according to ProtonMails latest CSS, but you should see that the login page and also Inbox sidebar is dark, right?

**Comment by KaKi87** [comment]
Hey !
Any news on this ?
Thanks

**Comment by kontrollanten** [comment]
You should be able to see the dark theme on the login page and inbox sidebar. The rest is up for grab for whoever wants to improve it.

**Comment by KaKi87** [comment]
In other words, it's a _wontfix_. Fortunately, [ElectronMail](https://github.com/vladimiry/ElectronMail) has a dark theme that works. :)
