### ISSUE TITLE
Virus detected in the Squirrel framework

### ISSUE THREAD

**Issue by GalaxyHopper** [protonmail-desktop/application#205]
VirusTotal has detected a virus/malware PUA.OSX.Adware in Squirrel inside the framework folder.
I resolved it by manually updating the Squirrel framework.

**Comment by kontrollanten** [comment]
I'm not sure how to solve this. It sounds like we need to update `electron-builder` and do a new release?

**Comment by kontrollanten** [comment]
Are you using Windows? May it be related to this https://github.com/atom/atom/issues/16986 ?

**Comment by GalaxyHopper** [comment]
I'm using the macOS

**Comment by kontrollanten** [comment]
How did you manually update Squirrel?

**Comment by GalaxyHopper** [comment]
I downloaded the latest Squirrel.framework from https://github.com/Squirrel/Squirrel.Mac/releases
unzipped it and replaced the old one found here: /Applications/Protonmail\ Desktop.app/Contents/Frameworks/Squirrel.framework

**Comment by kontrollanten** [comment]
@GalaxyHopper This seems to be fixed in our latest release; https://www.virustotal.com/#/file/6de5a01198143fea4ea9df0f52a6214bd695daa90dc86a9f137467555e06027b/detection

Can you download the new version and verify?

**Comment by GalaxyHopper** [comment]
@kontrollanten I installed the new version and the files are clean. Thanks a lot!
