### ISSUE TITLE
Taskbar shortcut doesn't work

### ISSUE THREAD

**Issue by starndust31** [protonmail-desktop/application#228]
If I make a shortcut in the taskbar with beta 4 nothing happens.

**Comment by starndust31** [comment]
Just wanted to say that the same thing happens with beta 6

**Comment by starndust31** [comment]
Also this issue doesn't appear in version 0.5.9

**Comment by starndust31** [comment]
And also that the cursor will load for a moment when clicking the shortcut

**Comment by kontrollanten** [comment]
And it's Windows 7 you are using? Can you describe the steps to reproduce? I'm not a Windows user but I'll try to reproduce it and fix.

**Comment by starndust31** [comment]
No, I am on windows 10. Steps go like this.
1. Open Protonmail
2. Right click icon in taskbar
3. Click pin to taskbar
4. Close proton mail
5. Press icon

Nothing will happen

**Comment by kontrollanten** [comment]
Thanks for your explanation. I was able to reproduce and fix this in Windows 10. The latest version should have this fixed, please let me know if it works as expected.

**Comment by starndust31** [comment]
It works, but it kind of pauses for a moment before opening now.

**Comment by starndust31** [comment]
Like the cursor will become that circle loading thing for a moment before opening. While I feel like this didn't happen before in 0.5.9, I feel like now the pause is a bit annoying but tolerable.

**Comment by kontrollanten** [comment]
Thanks for quick response! The Electron API has changed in the latest version, and that's what has changed since 0.5.9. We're actually not doing anything more than listening on the event that gets triggered and then calls `window.open()`, so I'm not sure what we can do about the pause. But I'll have a look, or maybe @BeatPlus
