### ISSUE TITLE
Publish in the Snap Store

### ISSUE THREAD

**Issue by flexiondotorg** [protonmail-desktop/application#245]
Hey @kontrollanten I work on the Snapcraft team and would love to help get ProtonMail Desktop published in the Snap Store smiley

I'm a ProtonMail user myself, I've just tested the snap you have in your GitHub releases and it works a treat! I see you're using Circle CI, here is their documentation for publishing snaps in the store:

    https://circleci.com/docs/2.0/build-publish-snap-packages/
    https://circleci.com/blog/build-test-publish-snap-packages/

Once published, you'll have direct control of the publishing life cycle and users will get automatic updates. I'd love to feature ProtonMail Desktop as an editors pick and put together a social campaign to promote it. What additional help do you need to get ProtonMail Desktop published in the snap store?

**Comment by kontrollanten** [comment]
Thanks! Sounds terrific! I just saw that I've already created a private snap in the store called `protonmail-desktop-unofficial`. Do you have any opinions regarding the name?

A PR is welcome to add snap publish config to our Circle CI config.

Regarding the campaign. May it be that we'll get more downloads from users who doesn't already have a ProtonMail account when it's promoted in the Snap Store? If true, shall we add a link in the first screen ("Add account") to ProtonMail Signup? Do you have any other ideas about stuff we can optimize to get the most out of the campaign?

**Comment by kontrollanten** [comment]
I don't have access to any Linux computer right now so I can't do the setup. I hope to get this configured and published within a week or two.

**Comment by kontrollanten** [comment]
Thanks for the help! Now it's [published](https://snapcraft.io/protonmail-desktop-unofficial)!

**Comment by smuriu** [comment]
Hello,

I have no experience publishing to snap store myself. However, I notice the license indicated in snapcraft is proprietary (while I can see in the repo it is MIT; and of course, I'm writing this in your open source repo). Might have to do with your `SNAPCRAFT_LOGIN_FILE` config for circle ci?

This is not a major issue for me, but other users encountering the snap on snapcraft might be put off by the incorrect license indicated.
