### ISSUE TITLE
Max Account 6

### ISSUE THREAD

**Issue by Ussagui** [protonmail-desktop/application#285]
Is there a way to have more than 6 accounts logged?
I got a token access error if not wrong (when i add acc 7, acc 1 got disconnected)

**Comment by kontrollanten** [comment]
I can't see why it shouldn't be possible with more than 6 accounts, more than they may not be all visible in the sidebar. What do you mean with "token access error"? Does it work when you use the web client?

**Comment by Ussagui** [comment]
> I can't see why it shouldn't be possible with more than 6 accounts, more than they may not be all visible in the sidebar. What do you mean with "token access error"? Does it work when you use the web client?

So i just reproduced the error and toke some print screen to show
resume:
after having more than 6 acc logged the "1st" one that i logged got the error
"invalid access token"
"invalid input"
but i did nothing on that account, i was just adding a new one ...
![1](https://user-images.githubusercontent.com/4978197/56096811-cf846880-5eba-11e9-9b85-167c0c24b7b3.png)
![2](https://user-images.githubusercontent.com/4978197/56096812-d01cff00-5eba-11e9-991a-ee3e218d340c.png)
![3](https://user-images.githubusercontent.com/4978197/56096813-d01cff00-5eba-11e9-9bc8-12d20caffc52.png)

**Comment by kontrollanten** [comment]
Okay. And does this work when you login to mail.protonmail.com from 6 different tabs in a browser?

**Comment by kontrollanten** [comment]
I'll close this for now. Feel free to re-open if your answer to my last question is "yes", otherwise it's a ProtonMail limitation
