### ISSUE TITLE
Notification settings

### ISSUE THREAD

**Issue by tde-1** [protonmail-desktop/application#348]
Currently, when you receive a notification about a new email, it will display the sender and the subject of the email in the notification.

For privacy reasons, a notification preferences screen should allow you to change what the notifications reveal. Some options could include:

When messages arrive, display notifications that reveal:
- Both sender name and subject (as it currently is)
- Only sender name
- Neither name nor subject
- Disable notifications

The above I have referenced from the Signal messenger desktop app which has these options.

**Comment by kontrollanten** [comment]
Thanks for your feedback! We're only forwarding the notification that ProtonMail is sending, so I don't think this is anything that should be changed within the desktop client but instead in the web client.

**Comment by vladimiry** [comment]
> Neither name nor subject

This is the way https://github.com/vladimiry/ElectronMail app does it.
