### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by skyblue002** [protonmail-desktop/application#453]
I have protonmail-desktop 1.0.2-1.

It seems like the icon is improperly configured and the result is that there is no icon showing up in the MATE panel menu.

I tracked down the error and it seems like a symlink is improperly configured. The `/usr/share/pixmaps/protonmail-desktop.png` link is broken. It links to: `/lib/protonmail-desktop/app/static/Icon.png` which doesn't exist. The icon is actually in: `/lib/protonmail-desktop/app/static/Icon.png`

Deleting the symlink and then recreating an accurate one solved the problem:

```
sudo rm /usr/share/pixmaps/protonmail-desktop.png
sudo ln -s /lib/protonmail-desktop/app/images/Icon.png
```

I don't know if this issue has been fixed or if it's an issue specific to the AUR release. I got the app from the AUR repositories here: [AUR (en) - protonmail-desktop](https://aur.archlinux.org/packages/protonmail-desktop)

Great work on the app, by the way! It's wonderful to have a desktop app for ProtonMail, and other than this, it's been smooth sailing. :)

**Comment by kontrollanten** [comment]
Thanks for reporting!

> It links to: /lib/protonmail-desktop/app/static/Icon.png which doesn't exist. The icon is actually in: /lib/protonmail-desktop/app/static/Icon.png

Both paths seems equal?

I've no idea how the AUR package is packaged and if there's something that is done manually regarding the icons. Now 1.0.4 is released, hopefully it can solve it.

**Comment by skyblue002** [comment]
That was a typo, I apologize. The icon did exist, but the symlink pointed to the wrong location. I had to delete the symlink and create one to the accurate location. It was a while ago since I initially made this report, but I believe the answer lies in the code that I listed for fixing the issue. Specifically this line:
```
sudo ln -s /lib/protonmail-desktop/app/images/Icon.png
```

So, what you quoted should actually read like this:

> It links to: `/lib/protonmail-desktop/app/static/Icon.png` which doesn't exist. The icon is actually in: `/lib/protonmail-desktop/app/images/Icon.png`

I checked the package build file in AUR and it contains this line:
```
 ln -s ../../lib/$pkgname/app/static/Icon.png "$pkgdir/usr/share/pixmaps/$pkgname.png"
```

This might be responsible for the problem. Right now, the latest version of the app in AUR is 1.0.2-1. If that is older than the latest release you put out, then I can hope that the package maintainer will fix it when the new release is put out. If not, I can contact them on AUR. 

Let me know if this is the most recent version of the app. If it's not, I will wait. If it is, I'll report the issue on AUR.

**Comment by kontrollanten** [comment]
Thanks for providing more information! The latest version is 1.0.4, so please ask the package maintainer to ask him to update the version and see if that solves the problem.

**Comment by skyblue002** [comment]
Okay. I just flagged the package as outdated and added a note for the maintainer to keep an eye on the line for creating that symlink in the Build file. I'll let you know how it turns out when the new version of the package is released.

**Comment by albakham** [comment]
I just updated the AUR package, I hope I resolved the problem.

**Comment by albakham** [comment]
I just updated the AUR package, I hope I resolved the problem.

**Comment by skyblue002** [comment]
@albakham I installed the update, and the icon looks fixed. I even restarted the computer just to be sure.

When I checked the `.desktop` file to verify the version of the app, it just said `1.0`, not `1.0.4`. I'm not sure if it's intentional or if there's some restriction in the `.desktop` format, disallowing a second "." But, just in case this was a typo, I wanted to mention it.
