### ISSUE TITLE
Application never starts with maximize

### ISSUE THREAD

**Issue by huyndnse63331** [protonmail-desktop/application#475]
Hi, first of all, thanks for the project, really convenient for me.
I'm using Ubuntu 18.04.3 (amd64), when i press on Protonmail Desktop icon, it always starts with minimized, even though i maximized it, but it's the same again, i have to maximize the window everytime. Will this be considered fixing? Thanks

![image](https://user-images.githubusercontent.com/25204246/70319779-b53a3900-1855-11ea-8daa-fd0e395ed07e.png)

**Comment by kontrollanten** [comment]
Thanks for reporting! Currently I don't have time to fix it, but a PR is welcome. I think it may be fixed by removing `!win.isMaximized()` here https://github.com/protonmail-desktop/application/blob/master/src/main/helpers/window.js#L70
