### ISSUE TITLE
Building from source; general info; basic documentation?

### ISSUE THREAD

**Issue by Electron-007** [protonmail-desktop/application#476]
New to NodeJS. On Fedora 31, after installing nodejs-yarn and rpmdevtools:
     `$ nodejs-yarn run dist`
Attempts to build all possible packages for all possible architectures, which seems a bit much to start off with.

The file 'Protonmail Desktop (unofficial)-1.0.4.AppImage' in the 'dist' folder is then executable and runs after building; nothing needs root privileges, but there is an rpm as well ...

What is the app supposed to do rather than logging into Protonmail webmail? It looks the same as the webmail version in the browser to me. How well is it supposed to integrate with Kontact and KMail?

**Comment by kontrollanten** [comment]
The app is, more or less, just the webmail, but without the need to run it as a browser tab. :) You can have a look at https://github.com/vladimiry/ElectronMail for more advanced features.
