### ISSUE TITLE
Blurry Windows tray icon

### ISSUE THREAD

**Issue by BeatPlus** [protonmail-desktop/application#53]
Version 0.3.0. 
In windows the icon on the notification bar gets blurry.
![Windows tray](http://i.imgur.com/GppMtL1.png?1)
This might be a problem with the .ico files. My screen is not retina or anything with high DPI.

@pwnsdx Do you have any experience with this?

**Comment by Trumpy** [comment]
Same thing, icon looks funky in gnome favorite bar.

**Comment by pwnsdx** [comment]
Sorry for the late response, I don't have this issue on macOS

**Comment by ahoneybun** [comment]
I have kinda the same issue in Plasma. 
![screenshot_20170516_215330](https://cloud.githubusercontent.com/assets/4884946/26135265/64133c9c-3a82-11e7-8834-ce8b9132e8e3.png)

I'm guessing that the tray is not scaling it right or something. Most likely upstream.

**Comment by BeatPlus** [comment]
With the updates of electron, the icons now look good on my Windows setup. I am closing this issue but feel free to open if still exists on other distros
