### ISSUE TITLE
Reopening program after closing doesn't work (Manjaro)

### ISSUE THREAD

**Issue by brogan89** [protonmail-desktop/application#536]
I have an issue where if I close the window and try to reopen it nothing will happen. I have to kill all electron processes and protonmail-desktop process and it will open fine through the GUI.

If I try open from terminal using `protonmail-desktop` it returns 

```
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
APPIMAGE env is not defined, current application is not an AppImage
```

After killing all the processes and running `protonmail-desktop` it opens fine and returns message 

```
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
APPIMAGE env is not defined, current application is not an AppImage
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

So maybe this is a electron issue? Sorry I don't know much about electron apps.
I was hoping it would just run in the background so I can still receive notifications.

System specs:
```
OS: Manjaro Linux x86_64 
Kernel: 5.4.23-1-MANJARO
DE: Cinnamon 4.4.8
CPU: Intel i7-4790 (8) @ 4.000GHz 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 7811MiB / 15957MiB 
```

EDIT:
For got to mention I'm using `beta.protonmail.com` as well - but it doesn't seem to make a different using beta or not. 

Also, I discovered that if i launch from terminal and use `ctrl+c` to exit or launch from GUI and use `xkill` to exit the application all the processes seemed to be terminated as well and I can reopen no problem.

**Comment by menaechmi** [comment]
Can confirm the same error on Arch running kernel 5.5.5-5.5.8, as well as on electron 8.1.0-2 and 8.1.1-1.

**Comment by brogan89** [comment]
Just installed the snap version on my Ubuntu laptop and everything works as expected. Seems to be related to the the arch and derivatives

**Comment by Syndamia** [comment]
On Linux Mint (Ubuntu based) I have a system tray icon with which I can toggle the app, but if I close it I can only reopen it from that icon, nothing happens if I try to open it from the menu. The same thing happens on my Manjaro pc but there isn't a tray icon with which I can reopen the window.

**Comment by kontrollanten** [comment]
Do you guys still have this issue? It sounds to be an issue related to electron, the latest version of protonmail-desktop has a newer version of electron which may work.

**Comment by brogan89** [comment]
> Do you guys still have this issue? It sounds to be an issue related to electron, the latest version of protonmail-desktop has a newer version of electron which may work.

Hi sorry I haven't been using Manjaro in a while but I booted up a VM right now and everything seems to work as expected. Must've been an electron issue. Thanks :)
