### ISSUE TITLE
This is actually a request

### ISSUE THREAD

**Issue by VandrerenErik** [protonmail-desktop/application#631]
The only thing stopping me from using this wonderful app is the lack of my password manager extension. Since this is an electron app it would be nice to have password manager like Bitwarden included. Having to write login in all of my accounts everytime the app repoens is a little bit of a pain. In the browser I have it easy with Bitwarden.

**Comment by kontrollanten** [comment]
Thanks @VandrerenErik ! I think this is duplicate of #90 I'll close this issue, subscribe to #90 to keep updated.

**Comment by VandrerenErik** [comment]
Similar but not the same and you looped both issues and closed both of them using the other as excuse...
